name: Check Project

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files
        run: ls -la

      - name: Project check
        run: echo "Fortune Teller project files are ready"